noecho

\ for MX130 breadboard

DECIMAL

\ LEDs
14 PORTB 2CONSTANT PWR_LED			\ GREEN
15 PORTB 2CONSTANT ACT_LED			\ RED

\ LCD
12 PORTB 2CONSTANT LCD_RS			\ LCD RS
3 PORTB 2CONSTANT LCD_EN			\ LCD E
6 PORTB 2CONSTANT LCD_D0			\ LCD DB0
7 PORTB 2CONSTANT LCD_D1			\ LCD DB1
8 PORTB 2CONSTANT LCD_D2			\ LCD DB2
9 PORTB 2CONSTANT LCD_D3			\ LCD DB3

\ Digital IO
11 PORTB 2CONSTANT DIO_PB1			\ PUSH BUTTON
2 PORTB 2CONSTANT RB2               \ pin 9
3 PORTB 2CONSTANT RB3               \ pin 10
13 PORTB 2CONSTANT RB13               \ pin 24

\ ADC
0 PORTA 2CONSTANT ADC_TEMP			\ pin 2 - AN0, Temperature
0 CONSTANT TEMP				        \ pin 2 - AN
2 PORTB 2CONSTANT ADC_VR    		\ pin 6 - AN4, VR
4 CONSTANT VOLTAGE                  \ pin 6 - AN4
13 PORTB 2CONSTANT ADC_AN11          \ pin 24 - AN11
11 CONSTANT AN11                    \ pin 24 - AN11
.( added breadboard ports)
echo
