noecho


\ for MX130 breadboard

DECIMAL

\ LEDs
14 PORTB 2CONSTANT PWR_LED			\ GREEN
15 PORTB 2CONSTANT ACT_LED			\ RED

\ LCD
12 PORTB 2CONSTANT LCD_RS			\ LCD RS
3 PORTB 2CONSTANT LCD_EN			\ LCD E
6 PORTB 2CONSTANT LCD_D0			\ LCD DB0
7 PORTB 2CONSTANT LCD_D1			\ LCD DB1
8 PORTB 2CONSTANT LCD_D2			\ LCD DB2
9 PORTB 2CONSTANT LCD_D3			\ LCD DB3

\ Digital IO
11 PORTB 2CONSTANT DIO_1			\ PUSH BUTTON

\ ADC
4 PORTA 2CONSTANT ADC_1				\ VR

.( added breadboard ports)
echo
