noecho


\ for MX130 breadboard

DECIMAL

\ LEDs
PORTB 14 2CONSTANT PWR_LED
PORTB 15 2CONSTANT ACT_LED
\ PORTB 15 CONSTANT TEST_LED

\ LCD
PORTB 12 2CONSTANT LCD_RS			\ LCD RS
PORTB 3 2CONSTANT LCD_EN			\ LCD E
PORTB 6 2CONSTANT LCD_D0			\ LCD DB0
PORTB 7 2CONSTANT LCD_D1			\ LCD DB1
PORTB 8 2CONSTANT LCD_D2			\ LCD DB2
PORTB 9 2CONSTANT LCD_D3			\ LCD DB3

\ Digital IO
PORTB 11 2CONSTANT DIO_1

\ ADC
PORTA 4 2CONSTANT ADC_1

echo
