noecho


\ for MX270 PCB

DECIMAL

\ LEDs
PORTA 8 2CONSTANT PWR_LED			\ GREEN -- Power
PORTC 4 2CONSTANT ACT_LED			\ GREEN -- Comms
PORTB 1 2CONSTANT ERROR_LED			\ RED -- Error


\ Digital IO
PORTB 0 2CONSTANT PB1			\ PUSH BUTTON - shared with programmer!

PORTC 5 2CONSTANT DIO_1			\ D1
PORTC 6 2CONSTANT DIO_2			\ D2
PORTC 7 2CONSTANT DIO_3			\ D3
PORTC 9 2CONSTANT DIO_4			\ D4


\ ADC
PORTC 0 2CONSTANT ADC_1				\ AN6 -- A1
PORTC 3 2CONSTANT ADC_2				\ AN12 -- A2
PORTB 3 2CONSTANT ADC_3				\ AN5 -- A3
PORTA 1 2CONSTANT ADC_4				\ AN1 - shared with debug serial! -- A4

6 CONSTANT TEMP				        \ AN6
12 CONSTANT VOLTAGE                  \ AN12
5 CONSTANT A3
1 CONSTANT A4

.( added pcb ports) CR
echo
